
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vehicleDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  client:
    image: nginx:alpine
    ports:
      - "3002:80"
    volumes:
      - ./apps/client/src:/usr/share/nginx/html:ro
  server:
    build:
      context: ./apps/server
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy